# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

vagrant_hostname = "robin"
vagrant_private = "192.168.66.10"
vagrant_gemport_host = 19292
vagrant_gemport_guest = 9292 
 
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # So the VM is recognisable
  config.vm.hostname = vagrant_hostname

  config.vm.provider "virtualbox" do |vb|
	# Just so we can see a VM running
	vb.gui = true
        vb.name = vagrant_hostname
	vb.memory = 4096
	vb.cpus = 2
  end

  config.vm.synced_folder "repo", "/vagrant-repo", mount_options: [ "ro" ]
  config.vm.synced_folder "scratch", "/vagrant-scratch", mount_options: [ "rw" ]

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "fionasboots/fedora21XfceMinimalPuppet"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: vagrant_gemport_guest, host: vagrant_gemport_host

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  # config.ssh.forward_agent = true

  config.ssh.username = "vagrant"
  
  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

end
